BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tournament
	(
	TournamentId int NOT NULL IDENTITY (1, 1),
	Name nvarchar(50) NOT NULL,
	SportId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tournament ADD CONSTRAINT
	PK_Tournament PRIMARY KEY CLUSTERED 
	(
	TournamentId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Tournament ADD CONSTRAINT
	FK_Tournament_Sport FOREIGN KEY
	(
	SportId
	) REFERENCES dbo.Sport
	(
	SportId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Tournament SET (LOCK_ESCALATION = TABLE)
GO
COMMIT