BEGIN TRANSACTION
GO
CREATE TABLE dbo.Bet
	(
	BetId int NOT NULL IDENTITY (1, 1),
	MatchId int NOT NULL,
	Status bit NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Bet ADD CONSTRAINT
	PK_Bet PRIMARY KEY CLUSTERED 
	(
	BetId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Bet ADD CONSTRAINT
	FK_Bet_Match FOREIGN KEY
	(
	MatchId
	) REFERENCES dbo.Match
	(
	MatchId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Bet SET (LOCK_ESCALATION = TABLE)
GO
COMMIT