BEGIN TRANSACTION
GO
CREATE TABLE dbo.BetRate
	(
	BetId int NOT NULL,
	RateId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.BetRate ADD CONSTRAINT
	PK_BetRate PRIMARY KEY CLUSTERED 
	(
	BetId,
	RateId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.BetRate ADD CONSTRAINT
	FK_BetRate_Bet FOREIGN KEY
	(
	BetId
	) REFERENCES dbo.Bet
	(
	BetId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BetRate ADD CONSTRAINT
	FK_BetRate_Rate FOREIGN KEY
	(
	RateId
	) REFERENCES dbo.Rate
	(
	RateId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BetRate SET (LOCK_ESCALATION = TABLE)
GO
COMMIT