BEGIN TRANSACTION
GO
CREATE TABLE dbo.EventBet
	(
	EventId int NOT NULL,
	BetId int NOT NULL,
	Coefficient float(53) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.EventBet ADD CONSTRAINT
	PK_EventBet PRIMARY KEY CLUSTERED 
	(
	EventId,
	BetId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.EventBet ADD CONSTRAINT
	FK_EventBet_Event FOREIGN KEY
	(
	EventId
	) REFERENCES dbo.Event
	(
	EventId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.EventBet ADD CONSTRAINT
	FK_EventBet_Bet FOREIGN KEY
	(
	BetId
	) REFERENCES dbo.Bet
	(
	BetId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.EventBet SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
