BEGIN TRANSACTION
GO
CREATE TABLE dbo.[User]
	(
	UserId int NOT NULL IDENTITY (1, 1),
	Login nvarchar(50) NOT NULL,
	Password nvarchar(50) NOT NULL,
	Email nvarchar(50) NOT NULL,
	Money money NULL,
	RoleId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.[User] ADD CONSTRAINT
	PK_User PRIMARY KEY CLUSTERED 
	(
	UserId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.[User] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT