BEGIN TRANSACTION
GO
CREATE TABLE dbo.RoleUser
	(
	RoleId int NOT NULL,
	UserId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.RoleUser ADD CONSTRAINT
	PK_RoleUser PRIMARY KEY CLUSTERED 
	(
	RoleId,
	UserId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.RoleUser ADD CONSTRAINT
	FK_RoleUser_Role FOREIGN KEY
	(
	RoleId
	) REFERENCES dbo.Role
	(
	RoleId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.RoleUser ADD CONSTRAINT
	FK_RoleUser_User FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.[User]
	(
	UserId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.RoleUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT