//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ToteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BetListDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class BetListDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinCommandGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinCommandHomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BetId {
            get {
                return this.BetIdField;
            }
            set {
                if ((this.BetIdField.Equals(value) != true)) {
                    this.BetIdField = value;
                    this.RaisePropertyChanged("BetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandGuest {
            get {
                return this.CommandGuestField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandGuestField, value) != true)) {
                    this.CommandGuestField = value;
                    this.RaisePropertyChanged("CommandGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandHome {
            get {
                return this.CommandHomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandHomeField, value) != true)) {
                    this.CommandHomeField = value;
                    this.RaisePropertyChanged("CommandHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Draw {
            get {
                return this.DrawField;
            }
            set {
                if ((this.DrawField.Equals(value) != true)) {
                    this.DrawField = value;
                    this.RaisePropertyChanged("Draw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinCommandGuest {
            get {
                return this.WinCommandGuestField;
            }
            set {
                if ((this.WinCommandGuestField.Equals(value) != true)) {
                    this.WinCommandGuestField = value;
                    this.RaisePropertyChanged("WinCommandGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinCommandHome {
            get {
                return this.WinCommandHomeField;
            }
            set {
                if ((this.WinCommandHomeField.Equals(value) != true)) {
                    this.WinCommandHomeField = value;
                    this.RaisePropertyChanged("WinCommandHome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class SportDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SportIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportId {
            get {
                return this.SportIdField;
            }
            set {
                if ((this.SportIdField.Equals(value) != true)) {
                    this.SportIdField = value;
                    this.RaisePropertyChanged("SportId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TournamentDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class TournamentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TournamentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportId {
            get {
                return this.SportIdField;
            }
            set {
                if ((this.SportIdField.Equals(value) != true)) {
                    this.SportIdField = value;
                    this.RaisePropertyChanged("SportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TournamentId {
            get {
                return this.TournamentIdField;
            }
            set {
                if ((this.TournamentIdField.Equals(value) != true)) {
                    this.TournamentIdField = value;
                    this.RaisePropertyChanged("TournamentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToteService.IRateListService")]
    public interface IRateListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetBets", ReplyAction="http://tempuri.org/IRateListService/GetBetsResponse")]
        Data.ToteService.BetListDto[] GetBets(System.Nullable<int> sportId, System.Nullable<int> tournamentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetBets", ReplyAction="http://tempuri.org/IRateListService/GetBetsResponse")]
        System.Threading.Tasks.Task<Data.ToteService.BetListDto[]> GetBetsAsync(System.Nullable<int> sportId, System.Nullable<int> tournamentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetBetsAll", ReplyAction="http://tempuri.org/IRateListService/GetBetsAllResponse")]
        Data.ToteService.BetListDto[] GetBetsAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetBetsAll", ReplyAction="http://tempuri.org/IRateListService/GetBetsAllResponse")]
        System.Threading.Tasks.Task<Data.ToteService.BetListDto[]> GetBetsAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetSport", ReplyAction="http://tempuri.org/IRateListService/GetSportResponse")]
        Data.ToteService.SportDto GetSport(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetSport", ReplyAction="http://tempuri.org/IRateListService/GetSportResponse")]
        System.Threading.Tasks.Task<Data.ToteService.SportDto> GetSportAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetSports", ReplyAction="http://tempuri.org/IRateListService/GetSportsResponse")]
        Data.ToteService.SportDto[] GetSports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetSports", ReplyAction="http://tempuri.org/IRateListService/GetSportsResponse")]
        System.Threading.Tasks.Task<Data.ToteService.SportDto[]> GetSportsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetTournament", ReplyAction="http://tempuri.org/IRateListService/GetTournamentResponse")]
        Data.ToteService.TournamentDto[] GetTournament(System.Nullable<int> sportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetTournament", ReplyAction="http://tempuri.org/IRateListService/GetTournamentResponse")]
        System.Threading.Tasks.Task<Data.ToteService.TournamentDto[]> GetTournamentAsync(System.Nullable<int> sportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetTournamentes", ReplyAction="http://tempuri.org/IRateListService/GetTournamentesResponse")]
        Data.ToteService.TournamentDto[] GetTournamentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateListService/GetTournamentes", ReplyAction="http://tempuri.org/IRateListService/GetTournamentesResponse")]
        System.Threading.Tasks.Task<Data.ToteService.TournamentDto[]> GetTournamentesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRateListServiceChannel : Data.ToteService.IRateListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateListServiceClient : System.ServiceModel.ClientBase<Data.ToteService.IRateListService>, Data.ToteService.IRateListService {
        
        public RateListServiceClient() {
        }
        
        public RateListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RateListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.ToteService.BetListDto[] GetBets(System.Nullable<int> sportId, System.Nullable<int> tournamentId) {
            return base.Channel.GetBets(sportId, tournamentId);
        }
        
        public System.Threading.Tasks.Task<Data.ToteService.BetListDto[]> GetBetsAsync(System.Nullable<int> sportId, System.Nullable<int> tournamentId) {
            return base.Channel.GetBetsAsync(sportId, tournamentId);
        }
        
        public Data.ToteService.BetListDto[] GetBetsAll() {
            return base.Channel.GetBetsAll();
        }
        
        public System.Threading.Tasks.Task<Data.ToteService.BetListDto[]> GetBetsAllAsync() {
            return base.Channel.GetBetsAllAsync();
        }
        
        public Data.ToteService.SportDto GetSport(System.Nullable<int> id) {
            return base.Channel.GetSport(id);
        }
        
        public System.Threading.Tasks.Task<Data.ToteService.SportDto> GetSportAsync(System.Nullable<int> id) {
            return base.Channel.GetSportAsync(id);
        }
        
        public Data.ToteService.SportDto[] GetSports() {
            return base.Channel.GetSports();
        }
        
        public System.Threading.Tasks.Task<Data.ToteService.SportDto[]> GetSportsAsync() {
            return base.Channel.GetSportsAsync();
        }
        
        public Data.ToteService.TournamentDto[] GetTournament(System.Nullable<int> sportId) {
            return base.Channel.GetTournament(sportId);
        }
        
        public System.Threading.Tasks.Task<Data.ToteService.TournamentDto[]> GetTournamentAsync(System.Nullable<int> sportId) {
            return base.Channel.GetTournamentAsync(sportId);
        }
        
        public Data.ToteService.TournamentDto[] GetTournamentes() {
            return base.Channel.GetTournamentes();
        }
        
        public System.Threading.Tasks.Task<Data.ToteService.TournamentDto[]> GetTournamentesAsync() {
            return base.Channel.GetTournamentesAsync();
        }
    }
}
