//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.TeamService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class TeamDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sport {
            get {
                return this.SportField;
            }
            set {
                if ((object.ReferenceEquals(this.SportField, value) != true)) {
                    this.SportField = value;
                    this.RaisePropertyChanged("Sport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportId {
            get {
                return this.SportIdField;
            }
            set {
                if ((this.SportIdField.Equals(value) != true)) {
                    this.SportIdField = value;
                    this.RaisePropertyChanged("SportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
    [System.SerializableAttribute()]
    public partial class CustomException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class MatchDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryGuestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryHomeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TournamentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TournamentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryGuest {
            get {
                return this.CountryGuestField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryGuestField, value) != true)) {
                    this.CountryGuestField = value;
                    this.RaisePropertyChanged("CountryGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryGuestId {
            get {
                return this.CountryGuestIdField;
            }
            set {
                if ((this.CountryGuestIdField.Equals(value) != true)) {
                    this.CountryGuestIdField = value;
                    this.RaisePropertyChanged("CountryGuestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryHome {
            get {
                return this.CountryHomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryHomeField, value) != true)) {
                    this.CountryHomeField = value;
                    this.RaisePropertyChanged("CountryHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryHomeId {
            get {
                return this.CountryHomeIdField;
            }
            set {
                if ((this.CountryHomeIdField.Equals(value) != true)) {
                    this.CountryHomeIdField = value;
                    this.RaisePropertyChanged("CountryHomeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultId {
            get {
                return this.ResultIdField;
            }
            set {
                if ((this.ResultIdField.Equals(value) != true)) {
                    this.ResultIdField = value;
                    this.RaisePropertyChanged("ResultId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreField, value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamGuest {
            get {
                return this.TeamGuestField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamGuestField, value) != true)) {
                    this.TeamGuestField = value;
                    this.RaisePropertyChanged("TeamGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamHome {
            get {
                return this.TeamHomeField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamHomeField, value) != true)) {
                    this.TeamHomeField = value;
                    this.RaisePropertyChanged("TeamHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamIdGuest {
            get {
                return this.TeamIdGuestField;
            }
            set {
                if ((this.TeamIdGuestField.Equals(value) != true)) {
                    this.TeamIdGuestField = value;
                    this.RaisePropertyChanged("TeamIdGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamIdHome {
            get {
                return this.TeamIdHomeField;
            }
            set {
                if ((this.TeamIdHomeField.Equals(value) != true)) {
                    this.TeamIdHomeField = value;
                    this.RaisePropertyChanged("TeamIdHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tournament {
            get {
                return this.TournamentField;
            }
            set {
                if ((object.ReferenceEquals(this.TournamentField, value) != true)) {
                    this.TournamentField = value;
                    this.RaisePropertyChanged("Tournament");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TournamentId {
            get {
                return this.TournamentIdField;
            }
            set {
                if ((this.TournamentIdField.Equals(value) != true)) {
                    this.TournamentIdField = value;
                    this.RaisePropertyChanged("TournamentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeamService.ITeamService")]
    public interface ITeamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeam", ReplyAction="http://tempuri.org/ITeamService/GetTeamResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/ITeamService/GetTeamCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        Data.TeamService.TeamDto[] GetTeam(System.Nullable<int> teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeam", ReplyAction="http://tempuri.org/ITeamService/GetTeamResponse")]
        System.Threading.Tasks.Task<Data.TeamService.TeamDto[]> GetTeamAsync(System.Nullable<int> teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeams", ReplyAction="http://tempuri.org/ITeamService/GetTeamsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/ITeamService/GetTeamsCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        Data.TeamService.TeamDto[] GetTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeams", ReplyAction="http://tempuri.org/ITeamService/GetTeamsResponse")]
        System.Threading.Tasks.Task<Data.TeamService.TeamDto[]> GetTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeamById", ReplyAction="http://tempuri.org/ITeamService/GetTeamByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/ITeamService/GetTeamByIdCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        Data.TeamService.TeamDto GetTeamById(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeamById", ReplyAction="http://tempuri.org/ITeamService/GetTeamByIdResponse")]
        System.Threading.Tasks.Task<Data.TeamService.TeamDto> GetTeamByIdAsync(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/UpdateTeam", ReplyAction="http://tempuri.org/ITeamService/UpdateTeamResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/ITeamService/UpdateTeamCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        bool UpdateTeam(Data.TeamService.TeamDto teamDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/UpdateTeam", ReplyAction="http://tempuri.org/ITeamService/UpdateTeamResponse")]
        System.Threading.Tasks.Task<bool> UpdateTeamAsync(Data.TeamService.TeamDto teamDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/AddTeam", ReplyAction="http://tempuri.org/ITeamService/AddTeamResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/ITeamService/AddTeamCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        bool AddTeam(Data.TeamService.TeamDto teamDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/AddTeam", ReplyAction="http://tempuri.org/ITeamService/AddTeamResponse")]
        System.Threading.Tasks.Task<bool> AddTeamAsync(Data.TeamService.TeamDto teamDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/DeleteTeam", ReplyAction="http://tempuri.org/ITeamService/DeleteTeamResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/ITeamService/DeleteTeamCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        bool DeleteTeam(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/DeleteTeam", ReplyAction="http://tempuri.org/ITeamService/DeleteTeamResponse")]
        System.Threading.Tasks.Task<bool> DeleteTeamAsync(int teamId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeamServiceChannel : Data.TeamService.ITeamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeamServiceClient : System.ServiceModel.ClientBase<Data.TeamService.ITeamService>, Data.TeamService.ITeamService {
        
        public TeamServiceClient() {
        }
        
        public TeamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.TeamService.TeamDto[] GetTeam(System.Nullable<int> teamId) {
            return base.Channel.GetTeam(teamId);
        }
        
        public System.Threading.Tasks.Task<Data.TeamService.TeamDto[]> GetTeamAsync(System.Nullable<int> teamId) {
            return base.Channel.GetTeamAsync(teamId);
        }
        
        public Data.TeamService.TeamDto[] GetTeams() {
            return base.Channel.GetTeams();
        }
        
        public System.Threading.Tasks.Task<Data.TeamService.TeamDto[]> GetTeamsAsync() {
            return base.Channel.GetTeamsAsync();
        }
        
        public Data.TeamService.TeamDto GetTeamById(int teamId) {
            return base.Channel.GetTeamById(teamId);
        }
        
        public System.Threading.Tasks.Task<Data.TeamService.TeamDto> GetTeamByIdAsync(int teamId) {
            return base.Channel.GetTeamByIdAsync(teamId);
        }
        
        public bool UpdateTeam(Data.TeamService.TeamDto teamDto) {
            return base.Channel.UpdateTeam(teamDto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTeamAsync(Data.TeamService.TeamDto teamDto) {
            return base.Channel.UpdateTeamAsync(teamDto);
        }
        
        public bool AddTeam(Data.TeamService.TeamDto teamDto) {
            return base.Channel.AddTeam(teamDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddTeamAsync(Data.TeamService.TeamDto teamDto) {
            return base.Channel.AddTeamAsync(teamDto);
        }
        
        public bool DeleteTeam(int teamId) {
            return base.Channel.DeleteTeam(teamId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTeamAsync(int teamId) {
            return base.Channel.DeleteTeamAsync(teamId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeamService.IMatchService")]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchesAll", ReplyAction="http://tempuri.org/IMatchService/GetMatchesAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/IMatchService/GetMatchesAllCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        Data.TeamService.MatchDto[] GetMatchesAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchesAll", ReplyAction="http://tempuri.org/IMatchService/GetMatchesAllResponse")]
        System.Threading.Tasks.Task<Data.TeamService.MatchDto[]> GetMatchesAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchById", ReplyAction="http://tempuri.org/IMatchService/GetMatchByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/IMatchService/GetMatchByIdCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        Data.TeamService.MatchDto GetMatchById(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchById", ReplyAction="http://tempuri.org/IMatchService/GetMatchByIdResponse")]
        System.Threading.Tasks.Task<Data.TeamService.MatchDto> GetMatchByIdAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/UpdateMatch", ReplyAction="http://tempuri.org/IMatchService/UpdateMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/IMatchService/UpdateMatchCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        bool UpdateMatch(Data.TeamService.MatchDto matchDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/UpdateMatch", ReplyAction="http://tempuri.org/IMatchService/UpdateMatchResponse")]
        System.Threading.Tasks.Task<bool> UpdateMatchAsync(Data.TeamService.MatchDto matchDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/AddMatch", ReplyAction="http://tempuri.org/IMatchService/AddMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/IMatchService/AddMatchCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        bool AddMatch(Data.TeamService.MatchDto matchDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/AddMatch", ReplyAction="http://tempuri.org/IMatchService/AddMatchResponse")]
        System.Threading.Tasks.Task<bool> AddMatchAsync(Data.TeamService.MatchDto matchDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/DeleteMatch", ReplyAction="http://tempuri.org/IMatchService/DeleteMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Data.TeamService.CustomException), Action="http://tempuri.org/IMatchService/DeleteMatchCustomExceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Service.Contracts.Exception")]
        bool DeleteMatch(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/DeleteMatch", ReplyAction="http://tempuri.org/IMatchService/DeleteMatchResponse")]
        System.Threading.Tasks.Task<bool> DeleteMatchAsync(int matchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : Data.TeamService.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.ClientBase<Data.TeamService.IMatchService>, Data.TeamService.IMatchService {
        
        public MatchServiceClient() {
        }
        
        public MatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.TeamService.MatchDto[] GetMatchesAll() {
            return base.Channel.GetMatchesAll();
        }
        
        public System.Threading.Tasks.Task<Data.TeamService.MatchDto[]> GetMatchesAllAsync() {
            return base.Channel.GetMatchesAllAsync();
        }
        
        public Data.TeamService.MatchDto GetMatchById(int matchId) {
            return base.Channel.GetMatchById(matchId);
        }
        
        public System.Threading.Tasks.Task<Data.TeamService.MatchDto> GetMatchByIdAsync(int matchId) {
            return base.Channel.GetMatchByIdAsync(matchId);
        }
        
        public bool UpdateMatch(Data.TeamService.MatchDto matchDto) {
            return base.Channel.UpdateMatch(matchDto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMatchAsync(Data.TeamService.MatchDto matchDto) {
            return base.Channel.UpdateMatchAsync(matchDto);
        }
        
        public bool AddMatch(Data.TeamService.MatchDto matchDto) {
            return base.Channel.AddMatch(matchDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddMatchAsync(Data.TeamService.MatchDto matchDto) {
            return base.Channel.AddMatchAsync(matchDto);
        }
        
        public bool DeleteMatch(int matchId) {
            return base.Channel.DeleteMatch(matchId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMatchAsync(int matchId) {
            return base.Channel.DeleteMatchAsync(matchId);
        }
    }
}
